### ISSUE TITLE
Swing.delete() method undefined variables

### ISSUE THREAD

**Issue by JamesNunns** [JamesNunns/Robotics-Group-Studies#12]
The Swing.delete() method references variables which are locally defined in the Swing.__init__(). These are not defined in .delete and so the method currently won't work. I recommend making them class attributes but that's your call, you could just redefine them.

**Comment by Ninstet** [comment]
Ah yes I need to do that. I only added that method for completeness, it isn't actually used yet but I'll fix it somepoint !
